### ISSUE TITLE
Existing tab gets replaced too

### ISSUE THREAD

**Issue by kikijiki** [Raphlette/obsidian-new-tab-plus#1]
If I have a tab open and I click a document, just before the new tab gets created the old one will too change to that document.
The result is that I end up with 2 tabs both with the same document.

**Comment by kikijiki** [comment]
Ah increasing the delay in the settings seems to fix it.

**Comment by Raphlette** [comment]
Yes I ended up having the same issue during the development process, that is why I added an adjustable delay. Depending on the computer (and maybe even the screen frame rate), the time for Obsidian to handle the original behavior of opening a file is sometime longer than my plugin execution. 
So yes adding more delay is helping troubleshooting this issue.
