### ISSUE TITLE
Doesn't work with Continuous Mode Plugin

### ISSUE THREAD

**Issue by lifehaschanged** [Raphlette/obsidian-new-tab-plus#3]
Hello and thank you for this useful plugin!

I'd be happy if you could test your plugin with this plugin enabled:

https://github.com/gasparschott/obsidian-continuous-mode

How to reproduce:
Open some tabs
Activate continuous mode from the right click menu
Open file explorer
Click on the files there that are open in the continuous mode

I have the setting enabled: "Check if file already open".

In my environment it's not switching to the tabs in this continuous mode, but it's opening new tabs instead or it overwrites the old tabs.

It would be very cool if you could make it work with this plugin enabled.

**Comment by Raphlette** [comment]
Hello, 
Thanks for your feedback ! 

At first glance, I would say that it might be a bit complicated to support non-standard features coming from other plugins, as it would require me to not only comply with Obsidian internal structure but also with new logics given by said features. 
Doing so would create way too much variables and use cases for me to take in account. 
So apart if I find a solution to cover more use cases with **New Tab +** in general, I don't think I can implement such support.

I'll have a look at it in the coming month though (Not so much free time at the moment) but I really can't promise anything. 

Keeping you updated.

**Comment by Raphlette** [comment]
Hi, as I said before, support on non-standard features coming from other plugins is not really realistic. Sorry, I won't go through with it. Hope you keep using it for the vanilla pages though :)

**Comment by Raphlette** [comment]
Hi @lifehaschanged,
I just had a look at the issue again as I was wrapping up the latest version of the plugin. 
New Tab + is more stable now, and when I tried with continuous mode it seemed to work well together.
Just little FYI, if you are still using both plugin, here it is :)
