### ISSUE TITLE
not work for obsidian of version v1.6.3

### ISSUE THREAD

**Issue by TrillStones** [Raphlette/obsidian-new-tab-plus#4]
SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 23.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Blue Topaz v2024040601
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 49
	Plugins enabled: 49
		1: Markmind v1.9.9
		2: QuickAdd v1.8.1
		3: Thino v2.4.47
		4: Templater v2.3.3
		5: Remember cursor position v1.0.9
		6: Excalidraw v2.2.6
		7: Dataview v0.5.66
		8: Advanced URI v1.40.1
		9: Note Refactor v1.8.2
		10: Better Word Count v0.10.1
		11: Clear Unused Images v1.1.0
		12: Auto Link Title v1.5.4
		13: Recent Files v1.4.1
		14: Tag Wrangler v0.6.1
		15: ExcaliBrain v0.2.15
		16: Breadcrumbs v3.6.11
		17: Enhancing Export v1.10.5
		18: Pandoc Plugin v0.4.1
		19: Git v2.24.2
		20: Custom Frames v2.4.7
		21: Linter v1.24.0
		22: ZotLit v1.1.5
		23: Editor Syntax Highlight v0.1.3
		24: Paste image rename v1.6.1
		25: File Explorer Note Count v1.2.2
		26: Spaced Repetition v1.12.4
		27: Settings Search v1.3.10
		28: Commander v0.5.1
		29: Whisper v1.5.5
		30: Text Generator v0.7.11
		31: Smart Connections v2.1.72
		32: Update time on edit v2.4.0
		33: Obsidian_to_Anki v3.6.0
		34: Persistent Links v0.2.0
		35: Copy Block Link v1.0.4
		36: Homepage v3.8.0
		37: BRAT v1.0.1
		38: AI Tagger v1.1.6
		39: DB Folder v3.5.1
		40: Supercharged Links v0.12.1
		41: Style Settings v1.0.8
		42: Strange New Worlds v2.1.4
		43: Emoji Magic v0.2.2
		44: Floating Search v3.5.1
		45: AttachFlow v0.4.3
		46: Image Toolkit v1.4.1
		47: Periodic Notes v0.0.17
		48: Calendar v1.5.10
		49: New Tab + v1.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Raphlette** [comment]
Thanks for the feedback ! I'll try to have a look at it within the week.

**Comment by Raphlette** [comment]
Hi ! In version 1.6.5, all features of the plugin works as expected :) I recommend to update Obsidian to latest version.
