### ISSUE TITLE
Nota duplicada

### ISSUE THREAD

**Issue by pablo-hp** [Raphlette/obsidian-new-tab-plus#7]
I have a fixed note.
I open a note.
I open another note.
For some reason, the first note (not the fixed note, but the first one I opened) becomes the second note, leaving two equal notes open.

**Comment by Raphlette** [comment]
Could you share a screenshot or screenrecord of the behavior so I could try to reproduce please ?

**Comment by pablo-hp** [comment]
Agradeço pela atenção.

Enviar imagens ou gravações, me faria expor conteúdos pessoais dos quais teria que fazer edição para não mostrar o conteúdo.

No entanto, considerando que disse em outro tópico, que o problema pode estar relacionado a plugin de terceiros, resolvi por hora apenas compartilhar a lista de plugins que tenho instalado e que podem estar ocasionando o problema.

Se este problema não ocorre em um ambiente normal, então, considero como sendo um problema de compatibilidade com algum outro plugin.

Segue imagem apenas para conhecimento.
Mas irei fechar o tópico, por entender se tratar de alguma incompatibilidade com outros plugins.

![Captura de tela 2024-09-27 150838](https://github.com/user-attachments/assets/03dc269d-3f76-4187-8f9d-262977e0efe1)
